"use client";

import { useRouter } from "next/navigation";
import { Icon } from "@/src/components/ui/icon";
import { useAppSettings } from "@/src/hooks/use-app-settings";

export default function TermsPage() {
  const router = useRouter();
  const s = useAppSettings();
  return (
    <div style={{ width:"100%", minHeight:"100dvh", background:"var(--bg)", display:"flex", flexDirection:"column" }}>
      <div style={{ display:"flex", alignItems:"center", gap:12, padding:"16px 20px", borderBottom:"1px solid var(--glass-border)", flexShrink:0 }}>
        <div className="top-nav-btn" onClick={() => router.back()}><Icon name="ArrowLeft" size={18} /></div>
        <h1 style={{ fontSize:17, fontWeight:700, margin:0, color:"var(--text)" }}>Términos y Condiciones</h1>
      </div>
      <div style={{ flex:1, overflowY:"auto", padding:"24px 20px 60px", color:"var(--text)", lineHeight:1.8, fontSize:14 }}>
        <p style={{ color:"var(--text-dim)", fontSize:12, marginBottom:24 }}>Última actualización: Julio de 2026</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>1. Introducción y Aceptación</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>1.1. Estos Términos y Condiciones (en adelante, los "Términos") constituyen un acuerdo legalmente vinculante entre usted (en adelante, el "Usuario" o "Usted") y {s.app_name} (en adelante, "{s.app_name}", "la Plataforma", "nosotros" o "el Prestador"), sociedad constituida y operando bajo las leyes de la República de Colombia.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>1.2. Al registrarse, acceder, utilizar o descargar la aplicación móvil o web de {s.app_name}, usted manifiesta de manera expresa, libre e inequívoca que ha leído, comprendido y aceptado en su totalidad estos Términos. Si usted no está de acuerdo con cualquiera de las disposiciones aquí contenidas, debe abstenerse de utilizar la Plataforma y, en caso de haberse registrado, proceder a la cancelación inmediata de su cuenta.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>1.3. {s.app_name} se reserva el derecho de modificar, actualizar o reemplazar estos Términos en cualquier momento. Las modificaciones entrarán en vigor desde el momento de su publicación en la Plataforma. Es responsabilidad exclusiva del Usuario revisar periódicamente estos Términos. El uso continuado de la Plataforma después de cualquier modificación constituye la aceptación tácita de los nuevos Términos. Cuando las modificaciones sean sustanciales, {s.app_name} notificará a los Usuarios mediante un aviso destacado en la Plataforma o a través del correo electrónico registrado.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>1.4. Para efectos legales y procesales, el domicilio del Prestador se fija en la ciudad de {s.legal_address}. Cualquier notificación judicial o extrajudicial deberá ser dirigida a la dirección de correo electrónico {s.legal_email}.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>2. Definiciones</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>Para los efectos de estos Términos, se entenderá por:</p>
        <p style={{ color:"var(--text-dim)", marginBottom:6 }}><strong>Plataforma:</strong> La aplicación web y móvil {s.app_name}, incluyendo todas sus funcionalidades, interfaces, APIs, bases de datos y código fuente asociado.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:6 }}><strong>Usuario:</strong> Toda persona natural mayor de edad que se registra y utiliza la Plataforma para la gestión de sus finanzas personales.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:6 }}><strong>Cuenta:</strong> El perfil personal creado por el Usuario mediante el registro en la Plataforma, protegido por credenciales de acceso (correo electrónico y contraseña).</p>
        <p style={{ color:"var(--text-dim)", marginBottom:6 }}><strong>Contenido del Usuario:</strong> Toda la información financiera, datos, categorías, movimientos, metas, presupuestos y configuraciones que el Usuario ingresa voluntariamente en la Plataforma.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:6 }}><strong>Servicio:</strong> El conjunto de funcionalidades ofrecidas por la Plataforma para el control financiero personal, incluyendo pero no limitado a: registro de ingresos y gastos, gestión de tarjetas de crédito, metas de ahorro, gastos fijos recurrentes, calendario financiero, estadísticas y notificaciones.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>3. Descripción y Alcance del Servicio</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>3.1. {s.app_name} es una aplicación de software diseñada exclusivamente para el control y la gestión de finanzas personales. La Plataforma permite a los Usuarios registrar, organizar y visualizar sus movimientos financieros de manera privada e individual.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>3.2. <strong>{s.app_name} NO es una entidad financiera.</strong> La Plataforma no está regulada por la Superintendencia Financiera de Colombia ni por ninguna otra autoridad financiera nacional o internacional. {s.app_name} no realiza, intermedia, ni facilita transacciones financieras reales. No ofrece productos de inversión, crédito, seguros, ni ningún otro servicio financiero regulado.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>3.3. <strong>La Plataforma NO constituye asesoría financiera.</strong> Toda la información mostrada en la Plataforma tiene carácter meramente informativo y organizativo. Las decisiones financieras que el Usuario tome basándose en los datos mostrados por la Plataforma son de su exclusiva responsabilidad. {s.app_name} no recomienda, sugiere ni avala ninguna decisión financiera específica.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>3.4. Las funcionalidades específicas de la Plataforma pueden incluir, sin limitarse a: (a) registro manual de ingresos y gastos con categorización; (b) gestión de múltiples fuentes de ingreso con diferentes frecuencias; (c) administración de tarjetas de crédito con fechas de corte y pago; (d) creación y seguimiento de metas de ahorro; (e) programación de gastos fijos recurrentes con alertas de vencimiento; (f) visualización de estadísticas y reportes financieros; (g) calendario financiero integrado; (h) notificaciones push y alertas configurables; (i) exportación y respaldo de datos.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>3.5. {s.app_name} se reserva el derecho de modificar, suspender o descontinuar cualquier funcionalidad de la Plataforma en cualquier momento, sin previo aviso y sin que ello genere derecho a indemnización alguna para el Usuario.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>4. Registro y Elegibilidad</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>4.1. Para utilizar la Plataforma, el Usuario debe: (a) ser una persona natural mayor de dieciocho (18) años; (b) tener capacidad legal para contratar según las leyes colombianas; (c) proporcionar información veraz, precisa, actualizada y completa durante el proceso de registro; (d) mantener y actualizar oportunamente dicha información para que se mantenga veraz y completa.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>4.2. El Usuario es el único responsable de: (a) mantener la confidencialidad de sus credenciales de acceso (correo electrónico y contraseña); (b) todas las actividades que ocurran bajo su cuenta, independientemente de si fueron autorizadas por el Usuario; (c) notificar inmediatamente a {s.app_name} sobre cualquier uso no autorizado de su cuenta o cualquier otra violación de seguridad.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>4.3. {s.app_name} no será responsable por ninguna pérdida o daño derivado del incumplimiento de las obligaciones de seguridad del Usuario establecidas en esta cláusula. El Usuario acepta que podrá ser considerado responsable por las pérdidas sufridas por {s.app_name} o por terceros debido al uso no autorizado de su cuenta.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>4.4. Cada Usuario puede mantener únicamente una (1) cuenta personal. Está prohibida la creación de cuentas múltiples, cuentas compartidas entre varias personas, o cuentas para uso comercial sin autorización expresa de {s.app_name}.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>5. Obligaciones y Conducta del Usuario</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>5.1. El Usuario se obliga a utilizar la Plataforma de conformidad con la ley, la moral, las buenas costumbres y el orden público, así como con lo dispuesto en estos Términos.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>5.2. Queda expresamente prohibido al Usuario: (a) utilizar la Plataforma con fines ilícitos, fraudulentos, difamatorios, obscenos o contrarios a la ley colombiana; (b) intentar acceder, modificar, copiar, distribuir, transmitir, exhibir, reproducir, publicar, licenciar o crear obras derivadas del código fuente de la Plataforma sin autorización previa y por escrito de {s.app_name}; (c) realizar ingeniería inversa, descompilar, desensamblar o de cualquier otra forma intentar extraer el código fuente de la Plataforma; (d) acceder o intentar acceder a los datos, cuentas o información de otros Usuarios sin su consentimiento expreso; (e) utilizar robots, spiders, scrapers, crawlers, o cualquier otro medio automatizado para acceder, extraer datos, o interactuar con la Plataforma; (f) interferir, interrumpir, dañar o sobrecargar los servidores, redes o infraestructura de la Plataforma; (g) introducir virus, malware, troyanos, gusanos, bombas lógicas o cualquier otro código malicioso; (h) suplantar la identidad de otra persona o entidad, o falsear su afiliación con cualquier persona o entidad; (i) acosar, intimidar, amenazar o causar daño a otros Usuarios o al personal de Nexora; (j) utilizar la Plataforma para enviar comunicaciones comerciales no solicitadas (spam).</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>5.3. El Usuario es el único responsable de la veracidad, exactitud, integridad y legalidad del Contenido que ingresa en la Plataforma. {s.app_name} no verifica, monitorea ni respalda el Contenido del Usuario.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>6. Propiedad Intelectual</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>6.1. Todos los derechos de propiedad intelectual sobre la Plataforma, incluyendo pero no limitado a: el código fuente, el código objeto, las interfaces de usuario, el diseño gráfico, los logotipos, las marcas, los nombres comerciales, los textos, las imágenes, los iconos, los gráficos, las animaciones, los vídeos, los sonidos, la arquitectura de software, las bases de datos, las APIs, los algoritmos, y cualquier otro elemento que forme parte de la Plataforma (en adelante, la "Propiedad Intelectual"), son de titularidad exclusiva de {s.app_name} o de sus licenciantes, y están protegidos por las leyes de propiedad intelectual de la República de Colombia (Decisión 351 de la Comisión del Acuerdo de Cartagena, Ley 23 de 1982, Ley 44 de 1993, y demás normas concordantes) y por los tratados internacionales aplicables.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>6.2. Ninguna disposición de estos Términos puede interpretarse como una concesión, transferencia, licencia o autorización de uso de la Propiedad Intelectual de {s.app_name}, salvo la licencia limitada, no exclusiva, intransferible y revocable que se otorga al Usuario para utilizar la Plataforma de acuerdo con estos Términos exclusivamente para su uso personal y no comercial.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>6.3. El Usuario conserva todos los derechos de propiedad sobre el Contenido que ingresa en la Plataforma. Al ingresar Contenido, el Usuario otorga a {s.app_name} una licencia limitada, no exclusiva, gratuita y mundial para usar, almacenar, reproducir, modificar y mostrar dicho Contenido exclusivamente con el fin de proporcionar, mantener y mejorar el Servicio. Esta licencia termina cuando el Usuario elimina su Contenido o su cuenta, sujeto a los períodos de retención descritos en la Política de Privacidad.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>6.4. El Usuario garantiza que el Contenido que ingresa en la Plataforma no infringe derechos de propiedad intelectual de terceros y se obliga a mantener indemne a {s.app_name} frente a cualquier reclamación de terceros relacionada con el Contenido del Usuario.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>7. Privacidad y Protección de Datos Personales</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>7.1. El tratamiento de los datos personales del Usuario se rige por la Política de Privacidad de {s.app_name}, la cual se incorpora por referencia a estos Términos y constituye parte integrante de los mismos. El Usuario declara haber leído y aceptado la Política de Privacidad.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>7.2. De conformidad con la Ley 1581 de 2012 (Ley de Protección de Datos Personales), el Decreto 1377 de 2013, y demás normas complementarias de la República de Colombia, el Usuario autoriza de manera expresa, libre, previa, voluntaria, informada e inequívoca a {s.app_name} para recolectar, almacenar, usar, procesar, transmitir y suprimir sus datos personales de acuerdo con lo establecido en la Política de Privacidad.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>7.3. {s.app_name} actúa como Responsable del Tratamiento de los datos personales de los Usuarios. Los datos de contacto del Responsable son: {s.app_name}, Bogotá D.C., Colombia, correo electrónico: {s.privacy_email}.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>7.4. El Usuario podrá ejercer sus derechos de acceso, consulta, rectificación, actualización, supresión y revocación del consentimiento en cualquier momento, mediante solicitud escrita dirigida al correo electrónico {s.privacy_email}, en los términos establecidos en la Ley 1581 de 2012.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>8. Seguridad de la Información</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>8.1. {s.app_name} implementa medidas de seguridad técnicas, administrativas y físicas razonables para proteger la información del Usuario contra acceso no autorizado, alteración, divulgación o destrucción, incluyendo: (a) cifrado de datos en tránsito mediante protocolo TLS (Transport Layer Security); (b) almacenamiento de contraseñas mediante funciones hash criptográficas irreversibles (scrypt); (c) cookies de sesión con atributos HttpOnly, Secure y SameSite=Strict; (d) validación de sesión mediante tokens almacenados en base de datos con fecha de expiración; (e) aislamiento estricto de datos por Usuario (cada query a la base de datos filtra por el identificador único de sesión); (f) rate limiting en endpoints sensibles (autenticación, mutaciones); (g) protección contra CSRF mediante validación de origen en el proxy del servidor.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>8.2. No obstante lo anterior, el Usuario reconoce y acepta que ningún sistema de seguridad es completamente infalible. {s.app_name} no puede garantizar la seguridad absoluta de la información transmitida a través de Internet. El Usuario asume los riesgos inherentes al uso de servicios en línea.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>9. Limitación de Responsabilidad</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>9.1. La Plataforma se proporciona "TAL CUAL" ("AS IS") y "SEGÚN DISPONIBILIDAD" ("AS AVAILABLE"), sin garantías de ningún tipo, ya sean expresas o implícitas, incluyendo pero no limitado a garantías de comerciabilidad, idoneidad para un propósito particular, no infracción, exactitud de los datos, o disponibilidad ininterrumpida del servicio.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>9.2. En la máxima medida permitida por la ley aplicable, {s.app_name}, sus directores, empleados, agentes, afiliados y proveedores no serán responsables por: (a) daños directos, indirectos, incidentales, especiales, consecuentes, punitivos o ejemplares de ningún tipo; (b) pérdida de beneficios, ingresos, datos, uso, fondo de comercio u otras pérdidas intangibles; (c) errores, inexactitudes u omisiones en el Contenido del Usuario; (d) decisiones financieras tomadas por el Usuario basándose en la información mostrada por la Plataforma; (e) interrupciones, suspensiones o terminación del Servicio; (f) virus, malware u otro código malicioso transmitido a través de la Plataforma por terceros; (g) cualquier daño resultante del acceso no autorizado, uso o alteración de las transmisiones o del Contenido del Usuario.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>9.3. Sin perjuicio de lo anterior, en caso de que un tribunal competente determine la responsabilidad de {s.app_name}, la responsabilidad total de {s.app_name} frente al Usuario por todos los daños, pérdidas y causas de acción (ya sea por contrato, responsabilidad extracontractual, o de otro tipo) no excederá, en ningún caso, el monto total pagado por el Usuario a {s.app_name} durante los doce (12) meses inmediatamente anteriores al hecho que generó la reclamación. Si el Usuario no ha realizado ningún pago, la responsabilidad máxima de {s.app_name} será de cero pesos colombianos (COP $0).</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>10. Indemnización</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>El Usuario se obliga a mantener indemne, defender y eximir de toda responsabilidad a {s.app_name}, sus afiliados, directores, empleados, agentes y proveedores frente a cualquier reclamación, demanda, daño, pérdida, costo, gasto (incluyendo honorarios razonables de abogados) derivados de: (a) el incumplimiento de estos Términos por parte del Usuario; (b) el Contenido ingresado por el Usuario en la Plataforma; (c) la violación de derechos de terceros por parte del Usuario; (d) el uso indebido o fraudulento de la Plataforma por parte del Usuario; (e) cualquier acto u omisión negligente, doloso o ilícito del Usuario.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>11. Suspensión y Terminación</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>11.1. {s.app_name} se reserva el derecho de suspender o terminar la cuenta del Usuario y/o el acceso a la Plataforma, en cualquier momento, con o sin causa, y con o sin previo aviso, en caso de: (a) violación de estos Términos; (b) uso fraudulento, ilegal o no autorizado de la Plataforma; (c) solicitud de una autoridad judicial o administrativa competente; (d) conducta del Usuario que {s.app_name} considere, a su entera discreción, perjudicial para la Plataforma, otros Usuarios o terceros; (e) inactividad prolongada de la cuenta, según los criterios que {s.app_name} establezca.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>11.2. El Usuario podrá cancelar su cuenta en cualquier momento a través de la configuración de la Plataforma o mediante solicitud al correo electrónico de soporte. La cancelación de la cuenta no exime al Usuario de las obligaciones pendientes derivadas de estos Términos.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>11.3. Tras la terminación de la cuenta, los datos del Usuario serán eliminados de acuerdo con lo establecido en la Política de Privacidad. Las disposiciones de estos Términos que por su naturaleza deban sobrevivir a la terminación (incluyendo propiedad intelectual, limitación de responsabilidad, indemnización y ley aplicable) permanecerán vigentes.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>12. Ley Aplicable y Jurisdicción</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>12.1. Estos Términos se rigen e interpretan de conformidad con las leyes de la República de Colombia, sin tener en cuenta sus principios de conflicto de leyes.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>12.2. Para la resolución de cualquier controversia que surja de o en relación con estos Términos o con el uso de la Plataforma, las partes se someten expresamente a la jurisdicción de los jueces y tribunales competentes de la ciudad de {s.legal_address}, renunciando a cualquier otro fuero o jurisdicción que pudiera corresponderles por razón de su domicilio presente o futuro.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>12.3. Antes de iniciar cualquier acción judicial, las partes se comprometen a intentar resolver sus diferencias de manera amistosa y de buena fe durante un período mínimo de treinta (30) días calendario, mediante comunicación escrita dirigida a la otra parte.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>12.4. En cumplimiento de lo dispuesto en la Ley 1480 de 2011 (Estatuto del Consumidor) y demás normas aplicables de la República de Colombia, el Usuario tiene derecho a presentar sus quejas o reclamos ante la Superintendencia de Industria y Comercio (SIC) en caso de considerar que sus derechos como consumidor han sido vulnerados.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>13. Disposiciones Generales</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>13.1. <strong>Acuerdo Completo.</strong> Estos Términos, junto con la Política de Privacidad y la Política de Cookies, constituyen el acuerdo completo entre el Usuario y {s.app_name} con respecto al uso de la Plataforma, y sustituyen cualquier acuerdo, comunicación o propuesta anterior, ya sea oral o escrita.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>13.2. <strong>Divisibilidad.</strong> Si cualquier disposición de estos Términos es declarada inválida, nula o inaplicable por un tribunal competente, dicha disposición se considerará separable y no afectará la validez y aplicabilidad de las disposiciones restantes.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>13.3. <strong>Renuncia.</strong> La falta de ejercicio por parte de {s.app_name} de cualquier derecho o disposición de estos Términos no constituirá una renuncia a dicho derecho o disposición. Ninguna renuncia será efectiva a menos que sea por escrito y esté firmada por un representante autorizado de {s.app_name}.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>13.4. <strong>Cesiones.</strong> El Usuario no podrá ceder, transferir ni subrogar sus derechos u obligaciones bajo estos Términos sin el consentimiento previo y por escrito de {s.app_name}. {s.app_name} podrá ceder libremente estos Términos sin restricción.</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>13.5. <strong>Notificaciones.</strong> Todas las notificaciones al Usuario se realizarán a través del correo electrónico registrado en su cuenta o mediante avisos publicados en la Plataforma. Se considerarán entregadas veinticuatro (24) horas después de su envío por correo electrónico, o inmediatamente después de su publicación en la Plataforma.</p>

        <h2 style={{ fontSize:18, fontWeight:700, marginTop:28, marginBottom:8 }}>14. Contacto</h2>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}>Para cualquier consulta, queja, reclamo o sugerencia relacionada con estos Términos, el Usuario puede contactar a {s.app_name} a través de los siguientes canales:</p>
        <p style={{ color:"var(--text-dim)", marginBottom:6 }}><strong>Correo electrónico:</strong> {s.legal_email}</p>
        <p style={{ color:"var(--text-dim)", marginBottom:6 }}><strong>Dirección:</strong> {s.legal_address}</p>
        <p style={{ color:"var(--text-dim)", marginBottom:12 }}><strong>Sitio web:</strong> {s.app_url || "http://localhost:3000"}</p>

      </div>
    </div>
  );
}
